import React from 'react';
import { 
  LayoutDashboard, 
  DollarSign, 
  Users, 
  Settings, 
  LogOut, 
  Plus, 
  Search, 
  Filter, 
  MoreVertical, 
  Edit2,
  UserPlus,
  X,
  ChevronDown,
  Lock,
  Mail,
  User,
  Download,
  Menu,
  Trash2,
  UserCog,
  BellRing
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Earnings: DollarSign,
  Members: Users,
  Settings: Settings,
  Logout: LogOut,
  Plus: Plus,
  Search: Search,
  Filter: Filter,
  More: MoreVertical,
  Edit: Edit2,
  Notification: BellRing,
  CreateUser: UserPlus,
  Close: X,
  Down: ChevronDown,
  Lock: Lock,
  Mail: Mail,
  User: User,
  Download: Download,
  Menu: Menu,
  Trash: Trash2,
  SystemUsers: UserCog
};